name: 'Branch Naming Convention'
on:
  create

jobs:
  branch-naming-rules-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'git hub ref'
        run: |
          echo github.event.ref_type
          echo github.github.event.ref

