name: 'Assert Branch Naming Convention'
on: create

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '(feature?|fix?|hotfix?|hf?|bug?)+\/(CMC-)\d+'
          allowed_prefixes: 'feature,fix,hotfix,hf,bug'
          ignore: master,main,2024.**
